packages:
  - packages/*
  - libs/*
  - apps/*
patchedDependencies:
  electron-vite: patches/electron-vite.patch
catalog:
  '@xsai-ext/providers-cloud': ^0.3.0-beta.8
  '@xsai-ext/providers-local': ^0.3.0-beta.8
  '@xsai/embed': ^0.3.0-beta.8
onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - bufferutil
  - electron
  - es5-ext
  - esbuild
  - sharp
  - unrs-resolver
  - utf-8-validate
  - vue-demi
  - websocket
