packages:
  - packages/*
  - libs/*
  - apps/*

patchedDependencies:
  electron-vite: patches/electron-vite.patch

catalog:
  '@unbird/eslint-config': ^1.0.1
  '@unbird/logg': ^1.1.0
  '@unbird/result': ^1.1.0
  '@xsai-ext/providers-cloud': ^0.3.3
  '@xsai-ext/providers-local': ^0.3.3
  '@xsai/embed': ^0.3.3

onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - bufferutil
  - electron
  - electron-winstaller
  - es5-ext
  - esbuild
  - sharp
  - unrs-resolver
  - utf-8-validate
  - vue-demi
  - websocket
