/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/ui/Avatar.vue')['default']
    Button: typeof import('./src/components/ui/Button/Button.vue')['default']
    ChatsCollapse: typeof import('./src/components/layout/ChatsCollapse.vue')['default']
    ChatSelector: typeof import('./src/components/ChatSelector.vue')['default']
    Dialog: typeof import('./src/components/ui/Dialog.vue')['default']
    MessageBubble: typeof import('./src/components/messages/MessageBubble.vue')['default']
    Pagination: typeof import('./src/components/ui/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchDialog: typeof import('./src/components/SearchDialog.vue')['default']
    SelectDropdown: typeof import('./src/components/ui/SelectDropdown.vue')['default']
    SettingsDialog: typeof import('./src/components/layout/SettingsDialog.vue')['default']
    SidebarSelector: typeof import('./src/components/layout/SidebarSelector.vue')['default']
    Stepper: typeof import('./src/components/ui/Stepper.vue')['default']
  }
}
