/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CommandList: typeof import('./src/components/commands/CommandList.vue')['default']
    ExportCommand: typeof import('./src/components/commands/ExportCommand.vue')['default']
    HighlightText: typeof import('./src/components/HighlightText.vue')['default']
    MessageBubble: typeof import('./src/components/MessageBubble.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SyncCommand: typeof import('./src/components/commands/SyncCommand.vue')['default']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
  }
}
